webInterface:
  url: "*"
  chrome:
    path: "driver\\chromedriver.exe"
  edge:
    path: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
safety:
  account: admin
  password: 123456%Yaxin
log:
  level: INFO
  filePath: '..\log\'
  format: '%(asctime)s - %(filename)s - [line:%(lineno)d] - [%(levelname)s]: %(message)s'